---
- hosts: all
  connection: local

  vars_files:
    - vars/vars.yaml
    - vars/passwords.yaml
    - vars/vcluster.yaml

  tasks:
    - name: Power on our test machine
      vmware_guest:
        hostname: "{{ VCENTER }}"
        username: "{{ USERNAME }}"
        password: "{{ PASSWORD }}"
        datacenter: Home
        #cluster: Cluster1
        name: win7.ad.dom.local
        state: poweredon
        validate_certs: false
        wait_for_ip_address: no
...
